import { User, TravelPlan, Review } from '@/types';

export const mockUsers: User[] = [
  {
    id: 'user-1',
    email: 'sarah@example.com',
    fullName: 'Sarah Johnson',
    role: 'user',
    profileImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
    bio: 'Adventure seeker and photographer. Love capturing moments from around the world.',
    travelInterests: ['Photography', 'Hiking', 'Local Cuisine'],
    visitedCountries: ['Thailand', 'Peru', 'Morocco', 'New Zealand'],
    currentLocation: 'San Francisco, USA',
    rating: 4.9,
    reviewCount: 32,
    verified: true,
  },
  {
    id: 'user-2',
    email: 'mike@example.com',
    fullName: 'Mike Chen',
    role: 'user',
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    bio: 'Tech entrepreneur exploring the world one city at a time.',
    travelInterests: ['Food Tours', 'Culture', 'Nightlife'],
    visitedCountries: ['Japan', 'South Korea', 'Singapore', 'Vietnam'],
    currentLocation: 'Tokyo, Japan',
    rating: 4.7,
    reviewCount: 18,
    verified: true,
  },
  {
    id: 'user-3',
    email: 'emma@example.com',
    fullName: 'Emma Williams',
    role: 'user',
    profileImage: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400',
    bio: 'Yoga instructor and wellness enthusiast. Seeking peaceful destinations.',
    travelInterests: ['Wellness', 'Beach', 'Meditation'],
    visitedCountries: ['Bali', 'India', 'Costa Rica', 'Greece'],
    currentLocation: 'Los Angeles, USA',
    rating: 5.0,
    reviewCount: 45,
    verified: true,
  },
  {
    id: 'user-4',
    email: 'alex@example.com',
    fullName: 'Alex Rodriguez',
    role: 'user',
    profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
    bio: 'History buff and museum lover. Always looking for the next historical site.',
    travelInterests: ['History', 'Museums', 'Architecture'],
    visitedCountries: ['Italy', 'Egypt', 'Turkey', 'Mexico'],
    currentLocation: 'Madrid, Spain',
    rating: 4.8,
    reviewCount: 27,
    verified: false,
  },
];

export const mockTravelPlans: TravelPlan[] = [
  {
    id: 'plan-1',
    userId: 'user-1',
    user: mockUsers[0],
    destination: 'Bali',
    country: 'Indonesia',
    startDate: '2024-06-15',
    endDate: '2024-06-25',
    budgetMin: 1500,
    budgetMax: 2500,
    travelType: 'Solo',
    description: 'Planning to explore temples, beaches, and try local cuisine. Looking for fellow travelers to share experiences!',
    interests: ['Beach', 'Culture', 'Food'],
    status: 'active',
    participants: [],
    createdAt: '2024-01-15',
  },
  {
    id: 'plan-2',
    userId: 'user-2',
    user: mockUsers[1],
    destination: 'Barcelona',
    country: 'Spain',
    startDate: '2024-07-01',
    endDate: '2024-07-10',
    budgetMin: 2000,
    budgetMax: 3500,
    travelType: 'Friends',
    description: 'Architecture tour, tapas crawling, and beach days. Want to make new friends!',
    interests: ['Architecture', 'Food', 'Nightlife'],
    status: 'active',
    participants: ['user-4'],
    createdAt: '2024-01-20',
  },
  {
    id: 'plan-3',
    userId: 'user-3',
    user: mockUsers[2],
    destination: 'Kyoto',
    country: 'Japan',
    startDate: '2024-05-10',
    endDate: '2024-05-20',
    budgetMin: 3000,
    budgetMax: 4000,
    travelType: 'Solo',
    description: 'Cherry blossom season! Temple visits, traditional tea ceremonies, and zen gardens.',
    interests: ['Culture', 'Photography', 'Meditation'],
    status: 'active',
    participants: [],
    createdAt: '2024-01-10',
  },
  {
    id: 'plan-4',
    userId: 'user-4',
    user: mockUsers[3],
    destination: 'Cairo',
    country: 'Egypt',
    startDate: '2024-08-15',
    endDate: '2024-08-25',
    budgetMin: 1800,
    budgetMax: 2800,
    travelType: 'Couple',
    description: 'Exploring pyramids, museums, and ancient Egyptian history.',
    interests: ['History', 'Architecture', 'Museums'],
    status: 'active',
    participants: [],
    createdAt: '2024-01-25',
  },
];

export const mockReviews: Review[] = [
  {
    id: 'review-1',
    fromUserId: 'user-2',
    toUserId: 'user-1',
    fromUser: mockUsers[1],
    rating: 5,
    comment: 'Sarah was an amazing travel companion! Great energy and very respectful. Highly recommend!',
    travelPlanId: 'plan-1',
    createdAt: '2024-01-05',
  },
  {
    id: 'review-2',
    fromUserId: 'user-3',
    toUserId: 'user-1',
    fromUser: mockUsers[2],
    rating: 5,
    comment: 'Had a wonderful time exploring together. Very organized and fun to be around.',
    createdAt: '2024-01-03',
  },
  {
    id: 'review-3',
    fromUserId: 'user-1',
    toUserId: 'user-2',
    fromUser: mockUsers[0],
    rating: 4,
    comment: 'Great guy! Very knowledgeable about local food scenes. Would travel again!',
    createdAt: '2023-12-28',
  },
];

export const popularDestinations = [
  {
    id: 'dest-1',
    name: 'Bali',
    country: 'Indonesia',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800',
    travelers: 156,
    description: 'Tropical paradise with temples and beaches',
  },
  {
    id: 'dest-2',
    name: 'Tokyo',
    country: 'Japan',
    image: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800',
    travelers: 243,
    description: 'Modern metropolis meets ancient traditions',
  },
  {
    id: 'dest-3',
    name: 'Paris',
    country: 'France',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800',
    travelers: 189,
    description: 'City of lights and romance',
  },
  {
    id: 'dest-4',
    name: 'Barcelona',
    country: 'Spain',
    image: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800',
    travelers: 167,
    description: 'Gaudi architecture and beach vibes',
  },
  {
    id: 'dest-5',
    name: 'New York',
    country: 'USA',
    image: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800',
    travelers: 312,
    description: 'The city that never sleeps',
  },
  {
    id: 'dest-6',
    name: 'Dubai',
    country: 'UAE',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800',
    travelers: 201,
    description: 'Luxury and desert adventures',
  },
];

export const testimonials = [
  {
    id: 'test-1',
    name: 'Jessica Martin',
    location: 'London, UK',
    image: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400',
    text: 'Found the perfect travel buddy for my Southeast Asia trip! We had similar interests and budget. Best decision ever!',
    rating: 5,
  },
  {
    id: 'test-2',
    name: 'David Park',
    location: 'Seoul, South Korea',
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400',
    text: 'This platform connected me with amazing people. We explored Europe together and became lifelong friends.',
    rating: 5,
  },
  {
    id: 'test-3',
    name: 'Maria Santos',
    location: 'Rio de Janeiro, Brazil',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400',
    text: 'Safe, easy to use, and perfect for solo travelers like me. Met wonderful companions who shared my love for adventure!',
    rating: 5,
  },
];
